---
- name: Deploy Apache web application
  hosts: slave1
  become: yes
  tasks:
    - name: Pull the Docker image
      docker_image:
        name: docker.io/ubuntu123am/my-apache-image
        source: pull
        state: present
